version: '3'
services:
  ntsoekhe-0:
    container_name: ntsoekhe-0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      ntoekhe-network:
        ipv4_address: 172.0.0.1

  ntsoekhe-1:
    container_name: ntsoekhe-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      ntoekhe-network:
        ipv4_address: 172.0.0.2
    
  ntsoekhe-2:
    container_name: ntsoekhe-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    networks:
      ntoekhe-network:
        ipv4_address: 172.0.0.3
  
  ntsoekhe-3:
    container_name: ntsoekhe-3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
    networks:
      ntoekhe-network:
        ipv4_address: 172.0.0.4
  
  ntsoekhe-4:
    container_name: ntsoekhe-4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
    networks:
      ntoekhe-network:
        ipv4_address: 172.0.0.5
networks:
  ntoekhe-network:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.254
          ip_range: 172.0.0.0/24